# Generated by Django 6.0 on 2026-01-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('service_type', models.IntegerField(choices=[(1, 'Cleaning'), (2, 'Repair'), (3, 'Moving'), (4, 'Construction'), (5, 'Other')])),
                ('description', models.TextField(blank=True, null=True)),
                ('base_duration_minutes', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
